### ISSUE TITLE
Filter Grid View

### ISSUE THREAD

**Issue by stephenap07** [stephenap07/gif-cabinet#6]
This should only be used on the Grid View. A user can filter the issues based on the following issue tags
• Open
• Closed
• Rejected
• Accepted

**Comment by jsncmgs1** [comment]
Select box is there, need back end functionality.  I would like to AJAX this in since our project is super small, I think we're gonna need it, I just need to know what paramter name to use, as well as value.  I'd recommend something like status for param name and simply the tag name as value, so /gif-cabinet?status=open

**Comment by jsncmgs1** [comment]
In fact to make it easy just go ahead and expect a parameter name of status on the back end, Stephen.

**Comment by stephenap07** [comment]
That's fine. I'll just render all the thumbnail.php templates when it gets that query string.

**Comment by jsncmgs1** [comment]
Sent a PR, url I'm using is grid-query.php but feel free to change it if you'd like.

**Comment by stephenap07** [comment]
Okay, I updated master with updated PHP as well.
